service: idp

provider:
  name: aws
  runtime: nodejs6.10
  stage: local
  environment:
    DB_ENCRYPTION_KEY: ${file(src/config/config.${self:provider.stage}.json):DB_ENCRYPTION_KEY}

functions:
  token:
    handler: src/handler.token
    events:
      - http:
          path: oauth/token
          method: post
  authorize:
    handler: src/handler.authorize
    events:
      - http:
          path: oauth/authorize
          method: get
  providers:
    handler: src/handler.providers
    events:
      - http:
          path: providers/{providerId}
          method: get
          parameters:
              paths:
                providerId: true
  callback:
    handler: src/handler.callback
    events:
      - http:
          path: callback/{providerId}
          method: get
          parameters:
              paths:
                providerId: true
          
  login:
    handler: src/handler.login
    events:
      - http:
          path: login
          method: post
      - http:
          path: login
          method: get
          
plugins:
  - serverless-webpack
  - serverless-offline