service: idp

provider:
  name: aws
  runtime: nodejs6.10
  stage: local
  environment:
    # Other
    DB_ENCRYPTION_KEY: ${file(src/config/config.${self:provider.stage}.json):DB_ENCRYPTION_KEY}
    # Tables
    CLIENTS_TABLE_NAME: ${self:custom.dynamo_clientsTable}
    CODES_TABLE_NAME: ${self:custom.dynamo_codesTable}
    PROVIDER_SESSIONS_TABLE_NAME: ${self:custom.dynamo_providerSessionsTable}
    PROVIDERS_TABLE_NAME: ${self:custom.dynamo_providersTable}
    SESSIONS_TABLE_NAME: ${self:custom.dynamo_sessionsTable}
    TOKENS_TABLE_NAME: ${self:custom.dynamo_tokensTable}
    USERS_TABLE_NAME: ${self:custom.dynamo_usersTable}

functions:
  token:
    handler: src/handler.token
    events:
      - http:
          path: oauth/token
          method: post
  authorize:
    handler: src/handler.authorize
    events:
      - http:
          path: oauth/authorize
          method: get
  providers:
    handler: src/handler.providers
    events:
      - http:
          path: providers/{providerId}
          method: get
          parameters:
              paths:
                providerId: true
  callback:
    handler: src/handler.callback
    events:
      - http:
          path: callback/{providerId}
          method: get
          parameters:
              paths:
                providerId: true
          
  login:
    handler: src/handler.login
    events:
      - http:
          path: login
          method: post
      - http:
          path: login
          method: get
          
resources:
  Resources:
    ClientsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_clientsTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: jwtSecret
            AttributeType: S
          - AttributeName: grantType
            AttributeType: S
          - AttributeName: redirectUris
            AttributeType: L
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ProvidersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_providersTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: clientSecret
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_usersTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: emailAddress
            AttributeType: S
          - AttributeName: emailVerified
            AttributeType: B
          - AttributeName: identities
            AttributeType: M
          - AttributeName: givenName
            AttributeType: S
          - AttributeName: familyName
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: pictureUrl
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CodesTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_codesTable}
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: redirectUri
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
          - AttributeName: subject
            AttributeType: S
          - AttributeName: created
            AttributeType: N
          - AttributeName: expires
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ProviderSessionsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_codesTable}
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: provider
            AttributeType: S
          - AttributeName: created
            AttributeType: N
          - AttributeName: expires
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SessionsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_sessionsTable}
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: redirectUri
            AttributeType: S
          - AttributeName: responseType
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
          - AttributeName: state
            AttributeType: S
          - AttributeName: created
            AttributeType: N
          - AttributeName: expires
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    TokensTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamo_tokensTable}
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
          - AttributeName: subject
            AttributeType: S
          - AttributeName: created
            AttributeType: N
          - AttributeName: expires
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamo_clientsTable: "clients_${opt:stage}_${self:service}"
  dynamo_codesTable: "codes_${opt:stage}_${self:service}"
  dynamo_providerSessionsTable: "providerSessions_${opt:stage}_${self:service}"
  dynamo_providersTable: "providers_${opt:stage}_${self:service}"
  dynamo_sessionsTable: "sessions_${opt:stage}_${self:service}"
  dynamo_tokensTable: "tokens_${opt:stage}_${self:service}"
  dynamo_usersTable: "users_${opt:stage}_${self:service}"

plugins:
  - serverless-webpack
  - serverless-offline