service: idp

provider:
  name: aws
  runtime: nodejs6.10

functions:
  token:
    handler: src/handler.token
    events:
      - http:
          path: oauth/token
          method: post
  authorize:
    handler: src/handler.authorize
    events:
      - http:
          path: oauth/authorize
          method: get
  login:
    handler: src/handler.login
    events:
      - http:
          path: login
          method: post
      - http:
          path: login
          method: get
          
plugins:
  - serverless-webpack
  - serverless-offline