service: idp

provider:
  name: aws
  runtime: nodejs6.10

functions:
  token:
    handler: handler.token
    events:
      - http:
          path: oauth/token
          method: get
  authorize:
    handler: handler.authorize
    events:
      - http:
          path: oauth/authorize
          method: get
          
plugins:
  - serverless-webpack
  - serverless-offline