service: idp

provider:
  name: aws
  runtime: nodejs6.10

functions:
  token:
    handler: functions/token.handle
    events:
      - http:
          path: oauth/token
          method: get
  authorize:
    handler: functions/authorize.handle
    events:
      - http:
          path: oauth/authorize
          method: get
          
plugins:
  - serverless-webpack